export { HomeTab } from './HomeTab'
export { NewsletterTab } from './NewsletterTab'
export { StoreTab } from './StoreTab'
export { CalculatorTab } from './CalculatorTab'
export { SettingsTab } from './SettingsTab'